//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sakura
{
    using System;
    using System.Collections.Generic;
    
    public partial class THOTEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THOTEL()
        {
            this.TPAQUETEPROGRAMADOes = new HashSet<TPAQUETEPROGRAMADO>();
            this.TVENTAPAQUETETURISTICOes = new HashSet<TVENTAPAQUETETURISTICO>();
        }
    
        public int CodHotel { get; set; }
        public int CodDestino { get; set; }
        public string NomHotel { get; set; }
        public string DireccionHotel { get; set; }
        public decimal precioHotel { get; set; }
        public string TelefonoHotel { get; set; }
        public string DetalleHotel { get; set; }
    
        public virtual TDESTINO TDESTINO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TPAQUETEPROGRAMADO> TPAQUETEPROGRAMADOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TVENTAPAQUETETURISTICO> TVENTAPAQUETETURISTICOes { get; set; }
    }
}
