//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sakura
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPAQUETEPROGRAMADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TPAQUETEPROGRAMADO()
        {
            this.TDETALLEVENTAs = new HashSet<TDETALLEVENTA>();
        }
    
        public int IDPaqueteProgramado { get; set; }
        public int CodPaqueteTuristico { get; set; }
        public int CodHotel { get; set; }
        public int CodDestino { get; set; }
        public string Observacion { get; set; }
    
        public virtual TDESTINO TDESTINO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDETALLEVENTA> TDETALLEVENTAs { get; set; }
        public virtual THOTEL THOTEL { get; set; }
        public virtual TPAQUETETURISTICO TPAQUETETURISTICO { get; set; }
    }
}
