//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sakura
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUSUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUSUARIO()
        {
            this.TVENTAPAQUETETURISTICOes = new HashSet<TVENTAPAQUETETURISTICO>();
        }
    
        public string Email { get; set; }
        public string NombreUsuario { get; set; }
        public string ApellidoPaternoUsuario { get; set; }
        public string ApellidoMaternoUsuario { get; set; }
        public Nullable<decimal> DNIUsuario { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string DireccionUsuario { get; set; }
        public string Sexo { get; set; }
        public string TelefonoUsuario { get; set; }
        public string clave { get; set; }
        public Nullable<int> Edad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TVENTAPAQUETETURISTICO> TVENTAPAQUETETURISTICOes { get; set; }
    }
}
