//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sakura
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVENTAPAQUETETURISTICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TVENTAPAQUETETURISTICO()
        {
            this.TDETALLEVENTAs = new HashSet<TDETALLEVENTA>();
        }
    
        public int IDVenta { get; set; }
        public string Email { get; set; }
        public int CodHotel { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public string Observacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDETALLEVENTA> TDETALLEVENTAs { get; set; }
        public virtual THOTEL THOTEL { get; set; }
        public virtual TUSUARIO TUSUARIO { get; set; }
    }
}
